# Настройки логирования сервиса

environment: "${APP_ENV}"

logging:
  level: debug # Logging level (debug, info, warning, error)
  file_output:
    file_path: "" # Path to the log file
    rotation_policy: monthly
    max_size_mb: 500
    max_backups: 50

# Server settings for processing client requests via REST API
client_connection_settings:
  gin_mode: "release" # Server operating mode (debug or release)
  port: "80" # Port and host on which the server is running
  host: "localhost" # Server
# List of sources that are allowed to access the REST API (CORS settings)
  allowed_origins:
    - "http://localhost:3000"


# Configuration of external services with which the auth service is integrated
external_service_integrations:
 # Settings for connecting to an SMTP server via gRPC to send email
  smtp_server:
    grpc:
      host: "" # Server address
      port: "" # Connection port

# Database configuration
database:
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  host: "" # Database server address
  port: "" # Database server port
  name: "" # Database name
  connection_timeout_seconds: 10
  max_pool_size: 50
  collections: # Names of the collections used
    auth_user: ""
    auth_tokens: ""
